#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Evento.Droid.Resource", IsApplication=true)]

namespace Evento.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int aaron = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ananth = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int background = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bob = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int chris = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int csharp = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int david = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int dean = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int demis = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int don = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int frank = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int greg = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Icon = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int igor = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int info = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int jb = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int jeremie = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int john_bubriski = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int john_zablocki = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int jonathan = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int louis = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int michael = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int miguel = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int paul = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int phil = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int rafaelc = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int sam = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int scott = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int somya = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int steve = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int tababout = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int tabsession = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int tabspeaker = 2130837536;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
	}
}
#pragma warning restore 1591
